### ISSUE TITLE
Different in JEI recipe and Research book

### ISSUE THREAD

**Issue by syamojin** [P3pp3rF1y/AncientWarfare2#733] opened 2018-07-06 07:02 UTC
when I make Light torque shaft, in JEI, unde this picture recipe
but it cannot make
![2018-07-06_16 01 16](https://user-images.githubusercontent.com/11242626/42364377-dede48f4-8135-11e8-803b-ad5e4bf31ccd.png)
and Research book recipe(true recipe)
![2018-07-06_16 02 04](https://user-images.githubusercontent.com/11242626/42364402-fb9033c2-8135-11e8-8e6c-b438a0242c48.png)

**Comment by syamojin** [comment] 2018-07-06 15:49
And I found Courier and Worker recipe is false.

**Comment by P3pp3rF1y** [comment] 2018-07-06 18:48
This is all caused by the same issue as #723 and #725 and I have it fixed in dev

**Closed as completed by P3pp3rF1y** 2018-07-06 18:48 UTC
