### ISSUE TITLE
Crash While Generating Bandit Castle

### ISSUE THREAD

**Issue by Blue001** [P3pp3rF1y/AncientWarfare2#519] opened 2017-01-24 21:42 UTC
A user on my server was exploring. And in the distance you can just make out a AW bandit castle starting to be created.

Then this crash happens, on client only. Server stays up.
So I went to crash myself there, and got the logs.

http://pastebin.com/X3ETMj01

Something to do with a mailbox?

(Another interesting thing about this whole situation is that on server creation I had I disabled all structure gen from AW, and yet they still occurred. I kinda shrugged at the time, but now that this is happening I wish the config file had worked and not allowed structure gen.)

a_world-gen_settings {
    # Default=true
    # Enable or disable structure generation entirely.
    B:enable_structure_generation=false

^^^^ Does nothing....

The only thing the server logs say is that something happened to disconnect the player... but it doesn't toss a crash or anything.

I've basically told my server users to not go over that way. So, temp fix? lol.
Anything you can do to help?

There is no way to disable mailboxes on the server using your configs that I can see (only the recipes), so I'm at a loss how to stop that particular crash in that area from happening.

**Comment by GotoLink** [comment] 2017-01-25 20:26
Since the crash is about rendering mailbox, i'll blame Optifine on this one.
Though i'll investigate the config issue (obviously for generation, it is the server config you need to change, just in case)

Also you can remove any generation template files from the mod (under assets/ancientwarfare/template)

**Comment by Blue001** [comment] 2017-01-25 21:08
Yeah I have that setting on the server itself.

For manually removing the templates, Are you talking open the mod jar with a zip program and pull them out of there? Because there is no asset folder on the server folder itself that I can see.

Is there a way you can make a config option to completely disable a block or item on the server so it vanishes if already present if the config is set to false? Right now there is just the recipe disable.

Thanks!

**Comment by P3pp3rF1y** [comment] 2017-12-08 19:25
Closing. I am not going to update 1.7.10 and confirmed this doesn't exist in 1.12

**Closed as completed by P3pp3rF1y** 2017-12-08 19:25 UTC
