### ISSUE TITLE
Tree Farm Block caused Server crash upon activation

### ISSUE THREAD

**Issue by Wrig13** [P3pp3rF1y/AncientWarfare2#1172] opened 2020-06-20 18:04 UTC
**The Issue tracker is mainly used for reporting bugs.**

New features, general discussion and suggestions should happen in our [Discord server](https://discord.gg/jNhkDfU). You'll also get your answers faster and can discuss with the dev team there.

Please use our [Discord server](https://discord.gg/jNhkDfU) for suggestions, we have a *#suggestions* channel for this purpose. We also have a list of all the existing suggestions [here](https://github.com/P3pp3rF1y/AncientWarfare2/wiki/Suggestions-List).

**The 1.7.10. version of the mod is not supported anymore, 1.12.2 is the actively developed version. Issues for the 1.7.10 version are automatically closed.**

Consult our other resources for more information about the mod: Treatise on principles of Ruling (Ingame Manual book), [Online Wiki](https://github.com/P3pp3rF1y/AncientWarfare2/wiki), [FAQ](https://github.com/P3pp3rF1y/AncientWarfare2/wiki/Frequently-Asked-Questions), [Discord FAQ](https://discordapp.com/channels/440863937777369088/501101121775992859/673303026911412228), [Announcements](https://discordapp.com/channels/440863937777369088/576129126381912064/576129530075283486)

## Context Environment
Minecraft version: 1.12.2

Ancient Warfare 2 version: ancientwarfare-1.12.2-2.7.0.772.jar

Minecraft Forge version: forge-14.23.5.2847

Link to your crash log (if the game crashes): https://pastebin.com/rGy78L8d

If you are using a modpack, link to the pack: https://www.curseforge.com/minecraft/modpacks/crackpack-3

## Expected Behavior
Tree Farm Block from Ancient Warfare Automation works

## Current Behavior
Placing Block in world and starting it, caused world to crash and unable to start back up without loading a backup which removed the entity from the world

## Steps to Reproduce
1. craft Tree Farm block
2. Place Tree Farm in world
3. Activate Tree Farm
4.

**Comment by ThatPolishKid99** [comment] 2020-06-20 19:22
Hi, can we get a bit more information? does this occur with vanilla saplings or with Forestry saplings? If it is with Forestry saplings, it is probably a duplicate of issue #1134

**Comment by Wrig13** [comment] 2020-06-21 12:23
Hello, yes this was with a forestry sailing.  I apologize for the duplicate report,  it looks like this issue was resolved from the previous thread.

**Closed as completed** 2020-07-07 12:31 UTC
