### ISSUE TITLE
Advanced monster spawner not working correctly

### ISSUE THREAD

**Issue by Durothan** [P3pp3rF1y/AncientWarfare2#864] opened 2018-12-23 18:29 UTC
Hi, I installed the latest version of advanced warfare and have an issue with the advanced monster spawner block not working. It currently does not seem to generate entities but only puts the name of the mob it should generate into the world. This results in random e.g. “Orc Lookout” nametags floating in the world. The mobs are not just invisible but rather inexistent as there is no way to interact with them. Is this a known issue and can it be fixed? I would appreciate a fast answer as this bug is pretty annoying. Thanks in advance for your help.
![2018-12-23_19 00 57](https://user-images.githubusercontent.com/43728822/50386539-04d93080-06e9-11e9-87e6-5babc1367560.png)

**Comment by ThatPolishKid99** [comment] 2018-12-23 18:33
Hi, you should be able to right click those and you'll be able to properly access the Spawner
They are transparent because those are prestocked structures which are designed to spawn their setting, and then disappear, making it appear as if the Mob was placed there. If you want these mobs to spawn as you're passing by, you should go into survival, and you'll see it working. 

As far as I can tell from what you've said, this is working as intended. I will close this for now, but feel free to open it back if the spawners are not working as I have described. 

Also, I recommend joining our Discord Server for quicker responses and discussion, as well as not making our issue tracker too cluttered. Here is the link: https://discord.gg/HZXeRcF

**Closed as completed by ThatPolishKid99** 2018-12-23 18:33 UTC
