### ISSUE TITLE
Structure Crash at Post-initialized

### ISSUE THREAD

**Issue by Mr-IE** [P3pp3rF1y/AncientWarfare2#514] opened 2016-12-12 00:50 UTC
http://pastebin.com/PyKhQ8WU
Got any suggestions?

**Comment by P3pp3rF1y** [comment] 2017-12-08 19:31
This was caused by Java 7 being used to run the mod. I don't think I am going back to supporting that in 1.12 so closing.

**Closed as completed by P3pp3rF1y** 2017-12-08 19:31 UTC
