### ISSUE TITLE
Courier Bug? and/or feature request(s).

### ISSUE THREAD

**Issue by Dark-Matter-001** [P3pp3rF1y/AncientWarfare2#470] opened 2016-03-15 21:27 UTC
When I define a stack size for a courier to deposit (seen here with eggs: http://i.imgur.com/UnQniMR.png ) it still just drops off everything it has in random amounts.  Is this a bug or a feature that doesn't exist yet?

If the second, would it be possible to implement a match stack size for drop offs?  In this current setup I need the courier to always drop an even number of eggs into a double chest with 2 hoppers on it to split the eggs evenly into 2 auto crafting tables.

..and while we're at it with the feature requests, a deposit 1/2 or deposit 1/4 button might be useful.  That way if you have a setup of 2 or 4 furnaces, the courier could split whatever its dropping off between them instead of all into the first. (If those 2 get added perhaps a button that cycles mode between All, 1/2, 1/4, Match? If UI space is an issue, remove could probably be replaced by just a red X? http://imgur.com/a/RJ7dX )

Another handy thing might be a wait timer so you could have something like: Drop stuff off in furnace -> wait 2 minutes -> pick stuff up from furnace.

**Comment by Trixtrox** [comment] 2016-03-20 01:46
I believe it is possible already to define a stack size. The problem is with the deposit matching command you are using.

"Deposit Matching
The Deposit Matching route type instructs the courier to deposit any items in his
backpack that match the filters specified for that point. The courier will continue to
deposit matching items until either his inventory is empty or the target inventory is full."

so the courier will fill the inventory with as many eggs as he can since eggs are in the filter. To put in a specific amount into an inventory use the fill target function.

"Fill Target
The Fill Target route type will see the courier attempt to fill the target inventory
with the specified quantities of the specified items. If the target inventory already
contains the specified amount, no action will be taken. The courier will continue to
deposit items into the target inventory until either the specified quantity is met or the
courier is out of the specified items"

That being said i do agree that it would be cool to have route orders with more functions. Especially because having a courier deposit goods evenly between two inventories would be great for dividing food among different town halls

**Comment by cosmicdan** [comment] 2016-05-29 15:25
Have a button cycle through all/exact/fill/ratio is a good idea. When I get some time, I will try and work on this.

**Comment by P3pp3rF1y** [comment] 2019-01-19 23:00
closing as features discussed here are already in the mod.

**Closed as completed by P3pp3rF1y** 2019-01-19 23:00 UTC
