### ISSUE TITLE
Commanders picking up everything to become soldiers

### ISSUE THREAD

**Issue by AspectSk** [P3pp3rF1y/AncientWarfare2#868] opened 2018-12-25 17:53 UTC
Commanders and medics just have the need to become a soldier, i get a commander to boost my troops but when in battle he just picks up every weapon and drops the baton, even though it does more damage, this is totally unlogical as they just pick it even if it is worse making it worse for them too because now the troops dont have a commander, i saw a post about this and you said that it is resolved, however i am here on the newest version and it is broken

**Comment by AspectSk** [comment] 2018-12-26 18:52
Well they dont, they will pick up an iron sword instead of keeping the diamond baton which is BETTER, i have the newest version also btw
Edit they will also pick up things like Wooden swords instead of a baton, its broken

**Comment by ThatPolishKid99** [comment] 2018-12-26 18:55
First, listen, buddy, this is just a commit, and unless you're downloading the absolute latest version from the maven, i don't think you have the version that has that fix. Second, the commit says they will only pick up a superior version of what is already in its hand. So a swordsman will only pick up a better sword, not a baton or something else. I will test the maven version now. Third, please be more respectful and don't immediately attack the developer.

**Comment by AspectSk** [comment] 2018-12-26 18:58
> First, listen, buddy, this is just a commit, and unless you're downloading the absolute latest version from the maven, i don't think you have the version that has that fix. Second, the commit says they will only pick up a superior version of what is already in its hand. So a swordsman will only pick up a better sword, not a baton or something else. I will test the maven version now. Third, please be more respectful and don't immediately attack the developer.

I wasnt attacking him, i am just frustrated not angry, i am however talking about commanders,medics and engineers picking up worse items as i already said, i dont have an issue with soldiers being better soldier i just have an issue about commanders, medics becoming soldiers even if it is worse for them and basically everyone
Edit: I also forgot to say that its good they are fixing this, thanks for clearing it up for me

**Comment by P3pp3rF1y** [comment] 2018-12-26 19:14
One more note - if the issue isn't closed the fix hasn't been released on curseforge so the only way to test the fix is using a dev build.

**Comment by AspectSk** [comment] 2018-12-27 13:44
> One more note - if the issue isn't closed the fix hasn't been released on curseforge so the only way to test the fix is using a dev build.

Yes i get that now

**Comment by P3pp3rF1y** [comment] 2018-12-27 13:47
Actually what I meant was that we will close once the fix is released so reopening until then

**Comment by P3pp3rF1y** [comment] 2019-01-06 21:26
the fix has been released

**Closed as completed by P3pp3rF1y** 2019-01-06 21:26 UTC
