### ISSUE TITLE
Faction standings reset to their defaults on server/world restart

### ISSUE THREAD

**Issue by MrTitainin** [P3pp3rF1y/AncientWarfare2#1044] opened 2019-10-07 19:21 UTC
MC 1.12.2  AW 2.7.0.722 forge 14.23.5.2838

Gained enough faction standing with Buffloka to visit their settlements safely, but after restart they attacked me, and it turns out that my faction standing with them is back to default. Same happened after killing a lot of Malices - their faction standing is back to default after reload, so no penalty for conquering them.

I guess they are not saved at all, rendering them basically useless.

**Comment by ThatPolishKid99** [comment] 2019-10-07 23:12
Hi, can we get your mod version and your complete modlist? Also could you please specify if you mean server or world reset? To me, server reset means loading the same world after stopping the server, while world reset means a completely new world is created. For the former, this would be an error, for the later, that would be intended behavior.

**Comment by MrTitainin** [comment] 2019-10-08 15:06
I added version to original post.

Server reset, that's why it's a problem. I mentioned "world restart" because it also happens in singleplayer, sorry for ambiguity in this matter. As for intended behaviour, there should be a command to reset those for all players (for example in case that config was modified) regardless of world restart.

About complete modlist: [LINK](https://pastebin.com/rVsgpaS7)
I'm too lazy to write them all so I just took logfile and modified it a bit - it's from clientside so it contains few unrelated mods, but I think it's no difference with that length anyway.

**Comment by MrTitainin** [comment] 2019-10-14 19:03
I forgot to mention that, but I modified configs (including the one with faction standings).

**Comment by P3pp3rF1y** [comment] 2019-10-30 19:54
I have this fixed in dev so marking as such

**Comment by ThatPolishKid99** [comment] 2021-02-12 18:09
Fixed in latest release

**Closed as completed by ThatPolishKid99** 2021-02-12 18:09 UTC
Labels: fixed in dev
