### ISSUE TITLE
Crash with latest version of AW

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#333] opened 2015-06-30 07:00 UTC
Time: 30/06/15 07:57
Description: Ticking entity

java.lang.NoSuchMethodError: java.util.List.sort(Ljava/util/Comparator;)V
    at net.shadowmage.ancientwarfare.npc.ai.NpcAIMedicBase.func_75250_a(NpcAIMedicBase.java:64)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:70)
    at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
    at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:708)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.shadowmage.ancientwarfare.npc.ai.NpcAIMedicBase.func_75250_a(NpcAIMedicBase.java:64)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:70)
    at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
    at net.shadowmage.ancientwarfare.npc.entity.NpcBase.func_70071_h_(NpcBase.java:708)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
    Entity Type: AncientWarfareNpc.bandit.priest (net.shadowmage.ancientwarfare.npc.entity.faction.NpcBanditPriest)
    Entity ID: 178975
    Entity Name: Heretic Priest
    Entity's Exact location: 445.49, 82.00, 535.20
    Entity's Block location: World: (445,82,535), Chunk: (at 13,5,7 in 27,33; contains blocks 432,0,528 to 447,255,543), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
    Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: Builder World One Eight
    All players: 1 total; [EntityPlayerMP['OldMiniCollector'/1369, l='Builder World One Eight', x=642.81, y=139.94, z=233.15]]
    Chunk stats: ServerChunkCache: 1465 Drop: 0
    Level seed: 1767110878880591893
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 2;7,59x1,3x3,2;1;stronghold,biome_1,village,decoration,dungeon,lake,mineshaft,lava_lake
    Level spawn location: World: (491,4,19), Chunk: (at 11,0,3 in 30,1; contains blocks 480,0,16 to 495,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 972555 game time, 1251693 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 23376 (now: false), thunder time: 105270 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_09, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 502206352 bytes (478 MB) / 2115895296 bytes (2017 MB) up to 3340566528 bytes (3185 MB)
    Mod Pack: Unknown / None
    LiteLoader Mods: 1 loaded mod(s)
          - MAtmos version r28 for 1.7.10
    LaunchWrapper: 27 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: poersch.minecraft.core.ClassPatcher
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: fastcraft.asm.FastCraftTransformer
          - Transformer: portablejim.fognerf.EntityRendererTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1792m -Xmx3584m -XX:PermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1264 Minecraft Forge 10.13.2.1264 74 mods loaded, 74 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1264} [Forge Mod Loader](forge-1.7.10-10.13.2.1264-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1264} [Minecraft Forge](forge-1.7.10-10.13.2.1264-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.3.74} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.74-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FamiliarsAPI{1.7.10} [Familiars API](FamiliarsAPI-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    lotr{Beta v23.3 for Minecraft 1.7.10} [The Lord of the Rings Mod]([1.7.10] The Lord of the Rings Mod B23.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bspkrsCore{6.14} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    StartingInventory{1.7.10.r02} [StartingInventory]([1.7.10]StartingInventory-universal-1.7.10.r02.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    aquacreeper{1.0b} [Aqua Creeper](AquaCreeper-1.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BetterSignsMod{1.6.4.B} [Better Signs Mod](BetterSignsMod[v1.7.10.ported].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bettervillages{0.4} [Better Villages Mod](BetterVillages-0.4%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.8.1} [BiblioCraft](BiblioCraft[v1.8.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    buildhelper{1.0.0} [Build Helper](BuildHelper_v1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Chimneys{1.7.2} [Chimneys](Chimneys-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    chocolateQuest{1.0} [Chocolate Quest](chocolateQuest-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    climatecontrol{0.4} [Climate Control](ClimateControl-0.4.beta17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    coralmod{1.7.10_dev} [CoralReef Mod](coralmod-1.7.10-3.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    nandocore{1.7.10_dev} [NandoCore](coralmod-1.7.10-3.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    scubadiving{1.7.10_dev} [Scuba Diving](coralmod-1.7.10-3.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    craftguide{1.6.8.1} [CraftGuide](CraftGuide-1.6.8.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CustomChestLoot{1.1.1} [Custom Chest Loot](CustomChestLoot-1.7.10-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    customnpcs{1.7.10d} [CustomNpcs](CustomNPCs_1.7.10d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    menagerie{1.0} [menagerie](dark_menagerie-1.7.10-beta-3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    props{1.11} [Decocraft](Decocraft-v1.11_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    doggystyle{1.0.4.77} [Doggy Style](DoggyStyle-1.0.5.78.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v6.3.1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    dungeonmobs{4.1.3} [Dungeon Mobs](Dungeon Mobs v4.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    eplus{1.7.10-3.0.1} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtrabiomesXL{3.16.2} [ExtrabiomesXL](extrabiomesxl_1.7.10-3.16.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtendedFamPack{1.7.10} [ExtendedFamPack](FamiliarsExtendedFamPack-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FastCraft{1.9} [FastCraft](fastcraft-1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    fognerf{1.7.10-0.3} [Fog Nerf](fognerf-1.7.10-0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    fossil{1.7.10 Build 7.1.0} [Fossils and Archeology Revival](Fossils_Archeology_Revival-1.7.10_Build-7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GardenCore{1.2.0} [Garden Core](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GardenContainers{1.2.1} [Garden Containers](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GardenTrees{1.2.0} [Garden Trees](GardenStuff-1.7.10-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GraveStone{2.12.3} [GraveStone](GraveStone-2.12.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3](GrimoireOfGaia3-1.7.10-1.0.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Highlands{2.2.3} [Highlands](Highlands-1.7.2-v-2.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    instantblocks{1.5.4} [Instant Blocks](InstantBlocks_v1.5.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    JASCompatability{1.1.0} [Just Another Spawner Compatibility Addon](JustAnotherSpawnerCompatibilityAddon-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LavaMonsters{2.2.1} [Lava Monsters](LavaMonsters-1.7.10-2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    lom{1.7.10-3.1.0} [LotsOMobs](lom-1.7.10-3.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MetallurgyCore{4.0.4} [Metallurgy Core](MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Metallurgy{4.0.6} [Metallurgy 4](Metallurgy-1.7.10-4.0.6.80.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    cfm{3.4.2} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.2%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    recipehandler{0.2} [NoMoreRecipeConflict](NoMoreRecipeConflict-0.2%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bonecraft{1.7.2b} [Pam's BoneCraft](Pam's BoneCraft 1.7.2b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    getalltheseeds{1.7.2a} [Pam's Get all the Seeds!](Pam's Get all the Seeds 1.7.2a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    harvestcraft{1.7.10g} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10g.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    simplerecipes{1.7.2a} [Pam's Simple Recipes](Pam's Simple Recipes 1.7.2a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    primitivemobs{1.1test} [Primitive Mobs](primitivemobs-1.1WIP.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjectZulu|Core{1.7.10-1.4c2} [Project Zulu](ProjectZulu-1.7.10-1.4c2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    reptilemod{1.7.10} [Reptile Mod](reptilemod-1.7.10-2.5.6-10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RopesPlus{1.6.3} [Ropes+](RopePlus-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    shipwrecks{1.7.0} [Shipwrecks!](shipwrecks-1.7.10-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    punt{1.7.10-10.13.0-15.0} [Punt](smallboats-1.7.10-10.13.0-15.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    whitehall{1.7.10-10.13.0-15.0} [Whitehall](smallboats-1.7.10-10.13.0-15.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    hoy{1.7.10-10.13.0-15.0} [Hoy](smallboats-1.7.10-10.13.0-15.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    smallboats{1.7.10-10.13.0-15.0} [SmallBoats (base)](smallboats-1.7.10-10.13.0-15.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    taverns{2.2.1-0} [Village Taverns](VillageTaverns-2.2.1-0.23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    wildcaves3{1.7.10} [Wild Caves 3](WildCaves3-0.4.3.7%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    witchery{0.23.2} [Witchery](witchery-1.7.10-0.23.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfare{2.4.105-beta-MC1.7.10} [Ancient Warfare Core](Zancientwarfare-2.4.105-beta-MC1.7.10-CORE.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareAutomation{2.4.105-beta-MC1.7.10} [Ancient Warfare Automation](Zancientwarfare-2.4.105-beta-MC1.7.10-AUTOMATION.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareNEIPlugin{2.4.105-beta-MC1.7.10} [Ancient Warfare NEI Plugin](Zancientwarfare-2.4.105-beta-MC1.7.10-CORE.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareNpc{2.4.105-beta-MC1.7.10} [Ancient Warfare NPCs](Zancientwarfare-2.4.105-beta-MC1.7.10-NPC.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AncientWarfareStructure{2.4.105-beta-MC1.7.10} [Ancient Warfare Structures](Zancientwarfare-2.4.105-beta-MC1.7.10-STRUCTURE.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    voxelmap{1.7.10} [VoxelMap No Radar](Zans-Minimap-No-Radar-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    JustAnotherSpawner{0.17.0} [Just Another Spawner](JustAnotherSpawner-0.17.0.DEV1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['OldMiniCollector'/1369, l='Builder World One Eight', x=642.81, y=139.94, z=233.15]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by GotoLink** [comment] 2015-06-30 09:54
Duplicate of #331

**Closed as completed by GotoLink** 2015-06-30 09:54 UTC
Labels: duplicate
