### ISSUE TITLE
Server Crash caused with ForgeEssentials fakeplayer entity check

### ISSUE THREAD

**Issue by Alaberti** [P3pp3rF1y/AncientWarfare2#387] opened 2015-09-13 18:14 UTC
I have brought this to the attention of their team, hoping more minds can help fix this problem.

http://pastebin.com/raw.php?i=2NRTwEjg
https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1622

**Comment by GotoLink** [comment] 2015-09-13 22:20
Duplicate of #352

**Closed as completed by GotoLink** 2015-09-13 22:20 UTC
Labels: duplicate

**Comment by Alaberti** [comment] 2015-09-14 15:09
My apologies.
