### ISSUE TITLE
Rendering Crash

### ISSUE THREAD

**Issue by mxnmnm** [P3pp3rF1y/AncientWarfare2#1187] opened 2020-07-29 05:37 UTC
## Context Environment
Minecraft version: 1.12.2

Ancient Warfare 2 version: 2.7.0.772

Minecraft Forge version: 14.23.5.2847

Link to your crash log (if the game crashes): https://gist.github.com/mxnmnm/a74a136abd77ad7414bfeb0e1cf1223d

This happened with some people I'm making a pack for and this is what they said they were doing:  "I placed down an object from it that had a witch burning at the stake, but the witch didn't appear, only the stake."

**Comment by mxnmnm** [comment] 2020-07-29 05:44
They were not able to log back into the world

**Comment by mxnmnm** [comment] 2020-07-29 06:09
Here is a modlist https://gist.github.com/mxnmnm/e45f3834a153176a69b4cf938de0cfd5

**Comment by SyndicMohawky** [comment] 2020-07-29 15:59
Its a known bug, fixed in dev.

**Comment by SyndicMohawky** [comment] 2020-07-29 15:59
You will have to remove the item using something like MCEdit

**Comment by WinDanesz** [comment] 2020-07-29 18:10
duplicate of #1037, #1180, #1111

**Closed as completed by WinDanesz** 2020-07-29 18:10 UTC
