### ISSUE TITLE
Soldiers（such as archer）will attack other mod's tamed entities, such as ice&fire‘s Hippogryph

### ISSUE THREAD

**Issue by MDusk** [P3pp3rF1y/AncientWarfare2#1184] opened 2020-07-26 02:56 UTC
**The Issue tracker is mainly used for reporting bugs.**

New features, general discussion and suggestions should happen in our [Discord server](https://discord.gg/jNhkDfU). You'll also get your answers faster and can discuss with the dev team there.

Please use our [Discord server](https://discord.gg/jNhkDfU) for suggestions, we have a *#suggestions* channel for this purpose. We also have a list of all the existing suggestions [here](https://github.com/P3pp3rF1y/AncientWarfare2/wiki/Suggestions-List).

**The 1.7.10. version of the mod is not supported anymore, 1.12.2 is the actively developed version. Issues for the 1.7.10 version are automatically closed.**

Consult our other resources for more information about the mod: Treatise on principles of Ruling (Ingame Manual book), [Online Wiki](https://github.com/P3pp3rF1y/AncientWarfare2/wiki), [FAQ](https://github.com/P3pp3rF1y/AncientWarfare2/wiki/Frequently-Asked-Questions), [Discord FAQ](https://discordapp.com/channels/440863937777369088/501101121775992859/673303026911412228), [Announcements](https://discordapp.com/channels/440863937777369088/576129126381912064/576129530075283486)

## Context Environment
Minecraft version:

Ancient Warfare 2 version:

Minecraft Forge version:

Link to your crash log (if the game crashes):

If you are using a modpack, link to the pack: 

## Steps to Reproduce
1.
2.
3.
4.

**Comment by ThatPolishKid99** [comment] 2020-07-26 06:24
Duplicate of Issue #1055, closing.

**Closed as completed by ThatPolishKid99** 2020-07-26 06:24 UTC
