### ISSUE TITLE
All NPCs Breaking Server When Approached

### ISSUE THREAD

**Issue by EiraTenn** [P3pp3rF1y/AncientWarfare2#347] opened 2015-07-06 18:58 UTC
Hi!
I started a small forge server with a couple of friends, but every time we get close to an (I would assume) AW structure, we crash the entire server and HAVE TO reset our player files to spawn. I was wondering if anyone else had ever had that problem, and if there was a way to disable the ticking mobs from spawning?

The full crash report:
http://pastebin.com/QZj2VQks

Thanks in advance!

**Comment by EiraTenn** [comment] 2015-07-06 20:16
EDIT: I did a bit of digging around, and it seems that this is a "duplicate issue" for which the solution is to install the newest version of Java. However, I tried updating Java, but it still gives the exact same result. 
Forge Ver: 10.13.2.1291

Shortly after, I tried updating it to Forge Ver 1.7.10-10.13.4.1472, resulting in minecraft simply not opening after clicking the Play button.

**Comment by Sandriell** [comment] 2015-07-07 02:10
Forge redid how it handles fluids in versions 1355+, so you will need to make sure all other mods are updated as well and that they can handle the new fluid system. That is more than likely the cause of minecraft failing to launch. Update all your mods and then post a newer crash report if it still fails.

**Comment by GotoLink** [comment] 2015-07-07 19:25
Fixed in build 107.

**Closed as completed by GotoLink** 2015-07-07 19:25 UTC
