### ISSUE TITLE
Upkeep order keeps crashing

### ISSUE THREAD

**Issue by YoungShinji** [P3pp3rF1y/AncientWarfare2#307] opened 2015-06-04 14:31 UTC
Hello,

Everytime when i try to right click the Upkeep order it keeps crashing.
I'm on a resonant rise mainline server

is there a solution ?

**Comment by bencrew** [comment] 2015-06-04 15:54
i am also having the same issue. the order crashes only after it has been bound with something

**Comment by GotoLink** [comment] 2015-06-05 13:00
Probably duplicate of #297
Missing crash report to make a difference.

**Comment by YoungShinji** [comment] 2015-06-09 08:05
Crash report > http://pastebin.com/AcMtU6pd

**Comment by GotoLink** [comment] 2015-06-21 15:44
Fixed in build 105.

**Closed as completed by GotoLink** 2015-06-21 15:44 UTC
Labels: duplicate
