### ISSUE TITLE
Inability to Move Soldiers Far From Town Hall

### ISSUE THREAD

**Issue by Sheepsys** [P3pp3rF1y/AncientWarfare2#630] opened 2018-03-31 22:35 UTC
Soldiers become hungry and begin gravitating towards a nearest town hall.

**Comment by P3pp3rF1y** [comment] 2018-04-04 09:52
I will need more info from you on what the issue is that you have. 
Is it that they walk to town hall after being spawned? 
Did you expect them to stay where you spawned them?
Did you try giving them a combat order so that they know where you want them to stay / patrol?

**Comment by P3pp3rF1y** [comment] 2018-04-19 21:52
Any update on this?

**Comment by P3pp3rF1y** [comment] 2018-04-28 10:24
Closing as there was no update

**Closed as completed by P3pp3rF1y** 2018-04-28 10:24 UTC
