### ISSUE TITLE
Hopper Support for Farms, Quarries, etc.

### ISSUE THREAD

**Issue by Divineaspect** [P3pp3rF1y/AncientWarfare2#178] opened 2014-12-01 03:06 UTC
I'd really like hopper support for farms, Quarries, and other inventoried machines.

**Comment by shadowmage45** [comment] 2014-12-01 16:24
It -should- already be present, but apparently there is a bug interfering with external inventory interaction at the moment.  Should have it cleaned up for the next bugfix release.

**Comment by shadowmage45** [comment] 2014-12-01 16:24
duplicate of #175

**Closed as completed by shadowmage45** 2014-12-01 16:24 UTC
Labels: duplicate

**Comment by wadewegner** [comment] 2016-03-20 13:53
I'm still having an issue with hopper support in latest build. Any pointers?
