### ISSUE TITLE
Bug: Fish Farm continues to fish even when inventory is full 

### ISSUE THREAD

**Issue by ThatPolishKid99** [P3pp3rF1y/AncientWarfare2#809] opened 2018-09-08 20:23 UTC
Just as the title says, here are some screenshots
![2018-09-08_15 20 27](https://user-images.githubusercontent.com/10103417/45258315-0faac800-b37b-11e8-9fe4-332383437b8e.png)
![2018-09-08_15 20 29](https://user-images.githubusercontent.com/10103417/45258316-0faac800-b37b-11e8-98a3-33323727b183.png)

**Comment by CharCharthemonkey** [comment] 2018-09-10 19:33
i can confirm the fishing farm works still without a fisher and no power (npc or torque or rf) input 
![2018-08-24_15 11 39](https://user-images.githubusercontent.com/30783285/45319804-76a8b800-b506-11e8-9fbb-f8889f773652.png)
![2018-08-24_16 23 54](https://user-images.githubusercontent.com/30783285/45319808-77414e80-b506-11e8-9dc9-3ce87348d7ab.png)

**Comment by P3pp3rF1y** [comment] 2018-09-10 19:34
That's because that fix isn't released yet, but it's fixed in dev.

**Comment by CharCharthemonkey** [comment] 2018-09-10 19:48
ohhh ok

**Closed as completed** 2018-09-23 22:12 UTC
Labels: bug, fixed in dev, Confirmed as bug
