### ISSUE TITLE
Stake error, can't remove it

### ISSUE THREAD

**Issue by AngelRed** [P3pp3rF1y/AncientWarfare2#1207] opened 2020-10-20 08:12 UTC
Minecraft version: 1.12.2
Minecraft Server SpongeForge 7.3.0 / Forge 14.23.5.2838

Ancient Warfare 2 version: 1.12.2-2.7.0.772

Link pastebin of tick error : https://pastebin.com/phNCgGs2

If you are using a modpack, link to the pack: https://www.curseforge.com/minecraft/modpacks/serveur-hestreia

## Expected Behavior

I except just to remove the stake by destroying him with anything (axe, pickaxe, tnt)
## Current Behavior

It can't be remove, i tried destroying it in creative, in survival with an axe, trying destroy it with //set 0 of world Edit

## Steps to Reproduce
1. Have my modpack Hestreia
2. Place stake
3. Try to remove it

**Comment by ThatPolishKid99** [comment] 2020-10-23 03:08
Duplicate of #1111

**Closed as completed by ThatPolishKid99** 2020-10-23 03:08 UTC
