### ISSUE TITLE
NPCs are invisible in generated structures

### ISSUE THREAD

**Issue by jaker1** [P3pp3rF1y/AncientWarfare2#1009] opened 2019-08-21 07:12 UTC
I got the problem with NPC in generated structures like castles, camp and etc. Minecraft shows their names, but they are turned to blocks and have no texture. However, when I try to spawn them myself, they appear normally. So what is the problem?

**Comment by P3pp3rF1y** [comment] 2019-08-21 13:50
And I am guessing you're in creative when they "are turned into blocks". That's because in creative the entities are not spawned in and stay in the spawner blocks. They will only spawn if you're in survival.

**Comment by jaker1** [comment] 2019-08-22 08:25
Oh, THANK YOU! And is there way to make them spawn in creative?

**Comment by P3pp3rF1y** [comment] 2019-08-22 09:44
No there isn't. Why would you actually need that to happen?

Also I am closing this as it's not a bug.

**Closed as completed by P3pp3rF1y** 2019-08-22 09:44 UTC

**Comment by jaker1** [comment] 2019-08-22 14:36
Ok, but it would be better if you mentioned that in the description of mod.
Thank you!

**Comment by jaker1** [comment] 2019-08-22 14:36
For the future
