### ISSUE TITLE
Ticking entity crash -- Seems to happen when Ancient warfare mobs fight each-other or other mobs (Crackpack 3)

### ISSUE THREAD

**Issue by KrazeDTv** [P3pp3rF1y/AncientWarfare2#1108] opened 2020-01-27 12:28 UTC
I was running around the forest and ran into some soldiers I think I didn't have anything to fight so I ran away and noticed a bunch of barbarians where close and they all started fighting. A few seconds later the game crashed. 

This issue happened to me in a different world also, I was in a stronghold and one of the elite mobs from the pack got annoyed with some witches and started killing them and i crashed then aswell. 

Crash: 1
https://paste.dimdev.org/ogelomopaf.sql

Crash: 2
https://paste.dimdev.org/oxufakajan.sql

**Comment by WinDanesz** [comment] 2020-01-27 13:24
Looks like some mob you have in that pack is overriding AW AI, its probably named Blood n Bones Gaming or something similar (com.bloodnbonesgaming.calmdownzombieguy). Remove this from your pack, or disable its AI injection/override in its config and try to reproduce the error.

**Comment by KrazeDTv** [comment] 2020-01-27 14:04
Thanks, ill have a look and let you know if it happens after.

Edit:
After looking at (com.bloodnbonesgaming.calmdownzombieguy) I found the mod which is actually apart of the Crack Pack 3 Mod list. 

Here is the mod https://www.curseforge.com/minecraft/mc-mods/calm-down-zombie-guy

It is used to stop zombies and pigmen attacking from different dimensions. 
So is one of the characters from Ancient Warfare based on a type of zombie? when it attacks it then gets overridden by this mod and causes conflict with the ai?

**Comment by P3pp3rF1y** [comment] 2020-05-27 20:49
I am unable to recreate any crash using this mod and the crash reports above are gone. If you're still around could you share those crashes again and the way this can be recreated? Otherwise the only thing I can do is just to close this.

**Comment by P3pp3rF1y** [comment] 2020-06-09 17:54
Closing

**Closed as completed by P3pp3rF1y** 2020-06-09 17:54 UTC
Labels: cannot confirm, Need info
