### ISSUE TITLE
NPC's vanishing

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#908] opened 2019-02-08 08:23 UTC
Nation NPC's are not being turned into spawner blocks when a player moves into and out of a structure multiple times. Instead they are vanishing/being removed from the whole structure.

**Comment by Cre8or** [comment] 2019-04-24 10:35
Looking forward to this fix, as it is currently possible to clear an entire castle _without ever using a weapon_.

Admittedly, it's a tedious and boring process of running in and out of the castle to despawn all enemies, but still - you can get access to every loot chest this way, and it defeats the entire point of having NPCs if you don't need to fight them first.

**Comment by kreezxil** [comment] 2019-05-07 20:54
How long does something stay in dev?

brand new world and I have invisible npcs.

![2019-05-07_15 52 00](https://user-images.githubusercontent.com/3880072/57332398-4c80b780-70e0-11e9-862b-3c64d6393c98.png)

on version 1.12.2-2.7.0.574

**Comment by kreezxil** [comment] 2019-05-07 20:56
![2019-05-07_15 56 01](https://user-images.githubusercontent.com/3880072/57332586-a3868c80-70e0-11e9-9b98-f6bdd3310f58.png)

**Comment by WinDanesz** [comment] 2019-05-07 20:56
Invisible NPCs? Are you in creative? Try switching to survival

**Comment by ThatPolishKid99** [comment] 2019-05-07 20:58
Hi, so first off, something will stay in dev until it is released, and we will release it when it is ready
Second, what you're seeing is intended behavior in creative mode. This issue is about despawning NPCs _after_ they have spawned, and don't revert back to spawner blocks as intended. Please read issues carefully.

**Comment by kreezxil** [comment] 2019-05-08 14:40
the issue seemed to fit, some devs get mad when you open obviously or
seemingly duplicate issues.

ok, thanks for the information about creative mode. Why is that a thing
tho? I've never seen another mod that does npcs use that behavior.

**Comment by ThatPolishKid99** [comment] 2019-05-08 14:43
It’s intended to improve performance. When in creative, the NPC don’t spawn, and only spawn when a player approaches in survival. When a player leaves, the NPCs revert back to Spawner blocks. In the latest release, that specific bit is a bugged, but it’s fixed in dev

**Comment by kreezxil** [comment] 2019-05-09 11:29
now that I understand that's a nice feature.

**Closed as completed** 2019-05-09 21:24 UTC
Labels: fixed in dev
