### ISSUE TITLE
Bug: AW Gates and Drawbridges jump in position when Valkyrien Warfare mod is installed 

### ISSUE THREAD

**Issue by ThatPolishKid99** [P3pp3rF1y/AncientWarfare2#829] opened 2018-09-22 17:29 UTC
This occurs on the most recent released version of AW, ancientwarfare-1.12.2-2.6.1.349, and Valkyrien Warfare version Valkyrien+Warfare+0.9_prerelease_5+[Optimization+Update]. 
![2018-09-22_12 26 25](https://user-images.githubusercontent.com/10103417/45919948-2a913800-be63-11e8-8bbb-9180b8ea4cc4.png)
![2018-09-22_12 26 27](https://user-images.githubusercontent.com/10103417/45919949-2a913800-be63-11e8-927c-b7f1a09f927d.png)
![2018-09-22_12 25 14](https://user-images.githubusercontent.com/10103417/45919950-2a913800-be63-11e8-96ab-7050b8181cc1.png)

**Comment by P3pp3rF1y** [comment] 2018-09-23 21:20
So i was going to at least try to see what VW is doing there, but they don't have a dev environment friendly build so I only got crashes on starting my environment. Anyway it looks like the mod still needs a lot done to it primarily to fix a lot of incompatibility issues with other mods. So this issue really should go to them as they are the cause of this rendering issue.

**Comment by P3pp3rF1y** [comment] 2018-11-12 08:59
closing this, nothing to be done on AW side

**Closed as completed by P3pp3rF1y** 2018-11-12 08:59 UTC
Labels: bug, Confirmed as bug
