### ISSUE TITLE
civic GUI too dark

### ISSUE THREAD

**Issue by gstv87** [P3pp3rF1y/AncientWarfare2#29] opened 2014-06-22 03:20 UTC
research, warehouse and similar GUIs are way too dark.... some slots don't stand out.
just a tad grey-er would be enough.
playing on laptop screen, 'moody' setting, optifineHD for 1.7.2, no extra brightness added.

**Comment by shadowmage45** [comment] 2014-06-22 17:11
I use the same color and lighting that is used in vanilla GUIs.

Can you provide a screenshot to illustrate the problem and ensure it is not a bug / issue with optifine/other mods?

**Comment by gstv87** [comment] 2014-06-22 18:12
http://i58.tinypic.com/259j2nn.jpg
http://i60.tinypic.com/2epj6hf.jpg
http://i59.tinypic.com/2qb7r7a.jpg

**Comment by shadowmage45** [comment] 2014-06-22 18:22
Thanks for the screenshots -- makes things much clearer :)

Those appear to be bugs.  All of those GUIs should be the standard gray color-scheme of vanilla GUIs.

Can you disable optifine and see if the issue persists? -- just trying to track down the source, which will help me know where to start looking for a proper solution.  Will also help me know what to do so that I can duplicate the issue (if I can't duplicate it, all I'm doing is -guessing- when I try to fix it).

**Comment by gstv87** [comment] 2014-06-22 18:47
nope..... no changes without optifine.
some parts do appear grey, though.... 
http://i60.tinypic.com/21b62c5.jpg

**Comment by shadowmage45** [comment] 2014-06-22 18:50
Just have to make sure -- are you running the most recent version (2.0.36)?  I did put in some fixes in an earlier release (.34 or so?) that should have prevented/fixed these problems.

**Comment by shadowmage45** [comment] 2014-06-22 19:09
I will be issuing an updated release shortly -- please check the releases section here in a few minutes.  I've updated my gui-rendering-init code to hopefully counter whatever is causing the black-backgrounds.  Please let me know if it is fixed with this next release (should be 2.0.37).

**Comment by gstv87** [comment] 2014-06-23 03:19
still black.
I disabled mods and texture packs to see if helped, but it didn't.
can't remember if I ever seen it grey,.... AFAIK, it's been always like that for me.
I'll try tracking down the issue from my end and see if I can narrow it down.

**Comment by shadowmage45** [comment] 2014-06-24 16:54
Is there any way I could have you test the GUIs on an install with -only- AW and forge setup?  

I need to try and eliminate other mods' as sources of problems, after which it is either a hardware conflict (not the most likely), or a bug in some code (mine or others..)

As you are not the only person experiencing this problem, there is likely a common shared cause -- hopefully a bit of investigation will help track it down.

**Comment by gstv87** [comment] 2014-06-25 04:26
just doing so right now

I did peek into the code to see if I could find a variable or something which would point me in the right direction, but I couldnt.... I tracked it up to net.minecraft.inventory.Container, but I don't have minecraft's source, so... :/

update: nope.... still black.... v2.0.40, no resource packs, no mods, no nothing.

**Comment by shadowmage45** [comment] 2014-10-29 00:23
Is this still a problem?  I could never confirm on my end, which leads me to suspect a driver problem of some sort.  Especially since the reports of the issue were mixed -- some people had problems while others did not.

Please re-open if this is still a problem and I will attempt further investigation.

**Closed as completed by shadowmage45** 2014-10-29 00:23 UTC
Labels: bug, cannot confirm
