### ISSUE TITLE
Derpy warehouse filters

### ISSUE THREAD

**Issue by CharCharthemonkey** [P3pp3rF1y/AncientWarfare2#811] opened 2018-09-10 19:34 UTC
as the name says the warehouse interface blocks filters are derpy 
![2018-09-10_12 40 21](https://user-images.githubusercontent.com/30783285/45319860-a22ba280-b506-11e8-88ee-e0a11688be65.png)
![2018-09-10_12 41 04](https://user-images.githubusercontent.com/30783285/45319874-aa83dd80-b506-11e8-88a5-c77c7ffa983d.png)

**Comment by P3pp3rF1y** [comment] 2018-09-10 19:37
So how did you actually get this. I assume you haven’t intentionally fill it like this, right? So steps to recreate would be good.

**Comment by CharCharthemonkey** [comment] 2018-09-10 19:42
set the filter to be shown as above have the items in the warehouse and it does it on its own basically

**Comment by ThatPolishKid99** [comment] 2018-09-10 21:04
Essentially, the filters when set to specific numbers don't always fill one stack before creating a new one, usually occurring only once per filter. In other words, the correct amount is put into the interface, but it sometimes takes up one than one slot when it should not be. This becomes a problem when multiple filters are being used in a single interface, resulting in some filtered items not being pushed to the interface when it should be, since its slot is filled by another filtered item being stack-split

 I can confirm seeing these stack issues multiple times, and while it can be easily fixed by taking the erring items out, it does happen again usually

**Closed as completed** 2018-09-23 22:12 UTC
Labels: bug, fixed in dev, Confirmed as bug
