### ISSUE TITLE
NPC Disappearing

### ISSUE THREAD

**Issue by ReggaeHorn** [P3pp3rF1y/AncientWarfare2#489] opened 2016-06-05 02:20 UTC
Hello, I have recently noticed that some NPC's have gone missing. I gave a soldier a patrol route, but he disappeared. He isn't dead, but he doesn't exist either. I don't know if this is a common problem, but I have noticed it happening quite a bit. I have lost all my soldiers, farmers, and a priest. There is no explanation to why this is happening other than they are despawning.

**Comment by cosmicdan** [comment] 2016-07-15 19:25
None of the NPC's can despawn, technically (they use the same code as vanilla Villagers in this respect) - so for all intents and purposes, they are "permanent".

It may be a bug in vanilla game, or your NPC's are getting lost, or they are dying outside the Town Center range.

Sadly, this kind of thing is practically impossible to fix without it being reproducible. But, in my fork I will try and add some creative-mode-only information/helpers for locating lost NPC's. I've added this to my Issue Tracker - https://github.com/cosmicdan/AncientWarfare2/issues/8

**Comment by cosmicdan** [comment] 2016-07-18 02:14
Can you please share information about how to reproduce? I can not fault it. Also give the full list of mods you have installed.

It may be caused by Optifine, if you are using it.

**Comment by erikuz** [comment] 2016-07-23 17:04
yes optifine can be reason of it

**Comment by P3pp3rF1y** [comment] 2018-04-28 14:37
Closing as said npcs are permanent and cant just despawn if you experience this in 1.12 please log a new issue.

**Closed as completed by P3pp3rF1y** 2018-04-28 14:37 UTC
Labels: cannot confirm
