### ISSUE TITLE
New World Crash

### ISSUE THREAD

**Issue by Janivire** [P3pp3rF1y/AncientWarfare2#183] opened 2014-12-06 18:22 UTC
I only have this mod installed on the newest forge, and every time i create a new world. this:
---- Minecraft Crash Report ----
// Sorry :(

Time: 12/6/14 11:38 AM
Description: Exception getting block type in world

java.lang.RuntimeException: Caught exception while constructing template blocks: Vanilla Block Rule id: minecraft:sticky_piston meta: 11 buildPass: 0
    at net.shadowmage.ancientwarfare.structure.template.build.StructureBuilder.instantConstruction(StructureBuilder.java:109)
    at net.shadowmage.ancientwarfare.structure.template.build.StructureBuilderWorldGen.instantConstruction(StructureBuilderWorldGen.java:140)
    at net.shadowmage.ancientwarfare.structure.world_gen.WorldStructureGenerator.generateStructureAt(WorldStructureGenerator.java:202)
    at net.shadowmage.ancientwarfare.structure.world_gen.WorldStructureGenerator.attemptStructureGenerationAt(WorldStructureGenerator.java:193)
    at net.shadowmage.ancientwarfare.structure.world_gen.WorldStructureGenerator.generateAt(WorldStructureGenerator.java:127)
    at net.shadowmage.ancientwarfare.structure.world_gen.WorldStructureGenerator.generate(WorldStructureGenerator.java:97)
    at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:106)
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055)
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
    at net.minecraft.world.World.func_72964_e(World.java:419)
    at net.minecraft.world.World.func_147439_a(World.java:345)
    at net.minecraft.world.World.func_147437_c(World.java:365)
    at net.minecraft.world.World.func_147474_b(World.java:329)
    at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71)
    at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:748)
    at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)
    at net.minecraft.world.World.<init>(World.java:260)
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NullPointerException
    at net.minecraft.world.WorldServer.func_147452_c(WorldServer.java:925)
    at net.minecraft.block.BlockPistonBase.func_150078_e(BlockPistonBase.java:139)
    at net.minecraft.block.BlockPistonBase.func_149726_b(BlockPistonBase.java:116)
    at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:655)
    at net.minecraft.world.World.func_147465_d(World.java:451)
    at net.shadowmage.ancientwarfare.structure.template.build.StructureBuilder.placeBlock(StructureBuilder.java:153)
    at net.shadowmage.ancientwarfare.structure.template.build.StructureBuilderWorldGen.placeBlock(StructureBuilderWorldGen.java:72)
    at net.shadowmage.ancientwarfare.structure.template.plugin.default_plugins.block_rules.TemplateRuleVanillaBlocks.handlePlacement(TemplateRuleVanillaBlocks.java:70)
    at net.shadowmage.ancientwarfare.structure.template.build.StructureBuilder.placeRule(StructureBuilder.java:215)
    at net.shadowmage.ancientwarfare.structure.template.build.StructureBuilder.placeCurrentPosition(StructureBuilder.java:184)
    at net.shadowmage.ancientwarfare.structure.template.build.StructureBuilder.instantConstruction(StructureBuilder.java:103)
    ... 25 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.shadowmage.ancientwarfare.structure.template.build.StructureBuilder.instantConstruction(StructureBuilder.java:109)
    at net.shadowmage.ancientwarfare.structure.template.build.StructureBuilderWorldGen.instantConstruction(StructureBuilderWorldGen.java:140)
    at net.shadowmage.ancientwarfare.structure.world_gen.WorldStructureGenerator.generateStructureAt(WorldStructureGenerator.java:202)
    at net.shadowmage.ancientwarfare.structure.world_gen.WorldStructureGenerator.attemptStructureGenerationAt(WorldStructureGenerator.java:193)
    at net.shadowmage.ancientwarfare.structure.world_gen.WorldStructureGenerator.generateAt(WorldStructureGenerator.java:127)
    at net.shadowmage.ancientwarfare.structure.world_gen.WorldStructureGenerator.generate(WorldStructureGenerator.java:97)
    at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:106)
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055)
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
    at net.minecraft.world.World.func_72964_e(World.java:419)

-- Requested block coordinates --
Details:
    Found chunk: true
    Location: World: (-26,64,210), Chunk: (at 6,4,2 in -2,13; contains blocks -32,0,208 to -17,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
    at net.minecraft.world.World.func_147439_a(World.java:345)
    at net.minecraft.world.World.func_147437_c(World.java:365)
    at net.minecraft.world.World.func_147474_b(World.java:329)
    at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:71)
    at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:748)
    at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:715)

-- Affected level --
Details:
    Level name: New Worl
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 314 Drop: 0
    Level seed: 2832111046784483180
    Level generator: ID 01 - flat, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 0 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.world.World.<init>(World.java:260)
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:97)
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_65, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1812825312 bytes (1728 MB) / 2098655232 bytes (2001 MB) up to 3006529536 bytes (2867 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn2G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1240 Minecraft Forge 10.13.2.1240 9 mods loaded, 9 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FML{7.10.85.1240} [Forge Mod Loader](forge-1.7.10-10.13.2.1240.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Forge{10.13.2.1240} [Minecraft Forge](forge-1.7.10-10.13.2.1240.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AncientWarfare{2.3.77-beta-MC1.7.10} [Ancient Warfare Core](ancientwarfare-2.3.77-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AncientWarfareAutomation{2.3.77-beta-MC1.7.10} [Ancient Warfare Automation](ancientwarfare-2.3.77-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AncientWarfareNEIPlugin{2.3.77-beta-MC1.7.10} [Ancient Warfare NEI Plugin](ancientwarfare-2.3.77-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AncientWarfareNpc{2.3.77-beta-MC1.7.10} [Ancient Warfare NPCs](ancientwarfare-2.3.77-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AncientWarfareStructure{2.3.77-beta-MC1.7.10} [Ancient Warfare Structures](ancientwarfare-2.3.77-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    AncientWarfareVehicle{2.3.77-beta-MC1.7.10} [Ancient Warfare Vehicles](ancientwarfare-2.3.77-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Profiler Position: N/A (disabled)
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Dulciphi** [comment] 2014-12-06 19:41
"Level generator: ID 01 - flat"

This is a known issue with structures containing pistons generating in a flat world. See #150 for more info.

Thank you

**Comment by Janivire** [comment] 2014-12-07 14:10
Ah thank you, i use flat worlds when testing mods.

**Comment by shadowmage45** [comment] 2014-12-08 18:37
Duplicate of #150

**Closed as completed by shadowmage45** 2014-12-08 18:37 UTC
Labels: duplicate
