### ISSUE TITLE
Text in Treatise seems to be stretched out, runs off the page

### ISSUE THREAD

**Issue by darthvader45** [P3pp3rF1y/AncientWarfare2#1018] opened 2019-08-25 19:59 UTC
I just looked at the Treatise on the Principles of Ruling and it seems the text goes off the page.  It doesn't seem to be resource pack related as I had the issue both with and without the John Smith Legacy resource pack v9 for 1.12.2.  Is there anything that can be done to fix the text?

**Comment by ThatPolishKid99** [comment] 2019-08-25 20:00
This is caused by optifine, and is supposedly fixed in the their latest pre-releases. Removing optifine will solve the problem regardless. Please join our discord for easier communication

**Closed as completed by ThatPolishKid99** 2019-08-25 20:00 UTC

**Comment by darthvader45** [comment] 2019-08-25 20:02
Thanks.  I'll try the latest pre-release.
