### ISSUE TITLE
NPC's running off in a straight line, indefinately. 

### ISSUE THREAD

**Issue by MohawkyMagoo** [P3pp3rF1y/AncientWarfare2#259] opened 2015-03-31 05:14 UTC
There is occasionally an odd behaviour of NPC's just setting off at a run from a spawned structure. It also happens sometimes when JAS spawns NPC's as mobs too. I thought at first they were chasing something, but they are not. Had one map where we were in a vanilla village that seemed to be on a migration route for orcs spawning in a nearby forest. It was very cool - hordes of them in waves - ended up being a bit Rorkes Drift. Or maybe Orc Drift? But it was definitely a bug of some sort as we were well out of activation range. Watched on creative the orcs eventually passed through the village and continued indefinitely off in the same direction.

Dulciphi has also noticed this:
"There is something I should mention with two Viking Priests I saw. They were running from one of the Viking temple structures. (the one with the bull horns or ...I don't know what that symbol is, sorry.) It was strange. The chunk had just been generated and everything seemed to generate just fine - but for some reason these two Priests just bolted, alone, and they seemed to go further than the 60 blocks or whatever their max pathing range is. I couldn't find any enemies or reason for them to be running from or to anything."

**Comment by Dulciphi** [comment] 2015-03-31 08:58
Question: Is this something to do with NPC's home points? 

I spawned 4 soldiers using AW2's custom spawner placer tool. I just plonked it down in the middle of a forest to see what would happen. As soon as the soldiers spawned, they all took off in the same direction - straight for a body of water. They went about 100 blocks or so and suddenly stopped, bobbing in the water together.  Attempts to move them from their position failed. That is to say, they were behaving as a player owned NPC behaves when one is "pushed" from their home point at night or when it's raining. 

As to why they all chose the same location, I'm at a loss. I can only think to ask if non-player owned NPCs have the same home point behaviour that player owned NPCs have. If they do, then spawning them may result in the observed behaviour. If that (or something similar) is the cause, would it be possible to have spawn point auto-assigned as home point in cases where no home point already exists?

**Comment by MohawkyMagoo** [comment] 2015-03-31 12:24
Sorry, should have said - this is Faction based NPC's and no home point set for them. But yes, the behaviour you describe is also what I'm seeing. Its not all the time, and not the same NPC types repeating it, its very random.

**Comment by GotoLink** [comment] 2015-05-22 19:09
Does it still apply in lastest version ? (build 104)

**Comment by P3pp3rF1y** [comment] 2018-05-07 21:51
this is not happening in 1.12, closing.

**Closed as completed by P3pp3rF1y** 2018-05-07 21:51 UTC
Labels: cannot confirm
