### ISSUE TITLE
Gates cause FPS drop

### ISSUE THREAD

**Issue by Lordician** [P3pp3rF1y/AncientWarfare2#1227] opened 2021-02-09 15:13 UTC
## Context Environment
Minecraft version: 1.12.2
Ancient Warfare 2 version: ancientwarfare-1.12.2-2.7.0.1027
Minecraft Forge version: 1.12.2 - 14.23.5.2854
Link to your crash log (if the game crashes): -
If you are using a modpack, link to the pack: -

## Current Behavior
While wandering through a town in Creative on a new world I started to notice my FPS drop when I looked at certain structures.
While tracking down the cause, I figured I might as well try to break some parts of certain possibly problematic structures (those where my FPS drops when I looked at them).
One of those structures was the Empire mage tower, I started to remove some animated firepits, but that did not do much if anything at all.
Then I removed the gates and my FPS increased from about 9-16 to 30-34.
This was with a total of two gates removed in the specific structure.
Aside of that, sometimes when i packed a gate, it left a ghost block called: ancientwarfarestructure:gate_proxy.

Logs: [logs.zip](https://github.com/P3pp3rF1y/AncientWarfare2/files/5952202/logs.zip)

## Steps to Reproduce
1. Start a new world with the latest versions of every mod and modloader (as described above).
2. Find a town (empire or other).
3. Find a structure with gates.
4. Remove gates for FPS increase.

## Possible Solution
-

**Comment by WinDanesz** [comment] 2021-02-09 18:21
Duplicate of #1226

**Closed as completed by WinDanesz** 2021-02-09 18:21 UTC
