### ISSUE TITLE
Crash when killing enemy NPCs

### ISSUE THREAD

**Issue by Neglevin** [P3pp3rF1y/AncientWarfare2#780] opened 2018-08-28 21:36 UTC
I got this crash when I killed an enemy npc: https://paste.dimdev.org/fusidajago.mccrash
I was using both the latest version of Forge and this mod.

**Comment by Neglevin** [comment] 2018-08-29 19:15
I forgot to add, I was also using the Better Invisibility mod and had a permanent form of invisibility on me using the Everlasting Abilities mod. Perhaps that could help in fixing it?

**Comment by P3pp3rF1y** [comment] 2018-08-31 18:47
yeah, so this is very likely issue with the mod that you have invisibility from. I guess what it does is that you're completely invisible to entities even when you attack them. 
And they reset revenge target of the entity at a wrong point which causes this crash because the vanilla hurt by entity ai needs to figure out if the revenge target is a friend. AW in fact doesn't do anything with setting revenge target so if this wasn't caused by some other mod it would be a vanilla issue, however I doubt that's the case.

**Comment by Neglevin** [comment] 2018-09-02 12:32
It seems to get fixed when I turn off the alert system in the Better Invisibility config, so it might be better now?

**Comment by P3pp3rF1y** [comment] 2018-09-02 13:22
I guess that concludes the Better invisibility mod is the cause of the issue here. In fact it will likely break other modded entities that use hurt by target ai. The mod is a closed source so hard to tell. 
Anyway I am closing this issue now.

**Closed as completed by P3pp3rF1y** 2018-09-02 13:22 UTC
