### ISSUE TITLE
Server Crash placing a block

### ISSUE THREAD

**Issue by voidswrath** [P3pp3rF1y/AncientWarfare2#1180] opened 2020-07-13 21:25 UTC
Server Crash while placing tile.stake.name.

Minecraft version: 1.12.2

Ancient Warfare 2 version: ancientwarfare-1.12.2-2.7.0.772 

Minecraft Forge version: 2854

Link to your crash log (if the game crashes): https://pastebin.com/z8Tw2LRA

**Comment by ThatPolishKid99** [comment] 2020-07-23 04:01
Closing, this is a duplicate of Issue #1037 and #1111 please refer to those on how to work around.

**Closed as completed by ThatPolishKid99** 2020-07-23 04:01 UTC
