### ISSUE TITLE
Modpack

### ISSUE THREAD

**Issue by TheBatski** [P3pp3rF1y/AncientWarfare2#268] opened 2015-04-12 19:33 UTC
can I add this into a modpack?

**Comment by GotoLink** [comment] 2015-04-12 20:04
Yes. If the mod is kept intact.
Generated files (config) are not part of the mod and can be altered in any way.
You can also change the mod, as long as GNU General Public License is kept, and changes are accessible to anyone.

**Comment by kane-thornwyrd** [comment] 2015-08-21 15:18
@TheBatski it's the general accepted conditions, by design, if you find a mod on the Curse network, that mean you can add it to a public modpack given you credit the authors and expose a link to the Minecraft Forum thread or the Github repo.

I think you can close this question.

**Comment by GotoLink** [comment] 2015-08-22 17:55
None of what Curse says may hold any ground whatsoever.
This mod has a license, which is the only legal text you need to abide by.
On no point can it be amended or restricted.

Question is left open for easy access to common users.

**Comment by P3pp3rF1y** [comment] 2018-04-29 22:52
Closing, AW uses GNU GPL v3 or later which is very common among mods so modpack devs should know what they're dealing with (and those that don't I doubt will look hear anyway). Also this is now buried deep in the issue list so people are unlikely to find it anyway.

**Closed as completed by P3pp3rF1y** 2018-04-29 22:52 UTC
Labels: question
