### ISSUE TITLE
Personal Structure Bug 

### ISSUE THREAD

**Issue by ThatPolishKid99** [P3pp3rF1y/AncientWarfare2#184] opened 2014-12-07 05:57 UTC
i am getting this crash whenever i load up either my Cauldron Server, or my Singleplayer, before i even open a world... I know it is linked to the building that i have scanned and have a template for. it works in the session in which i scan the building, but when i close Minecraft, or the Server, and the restart it, i get this crash...PLEASE HELP, this building is incredibly important to me
error doesn't occur when the template isn't in

<i apologize for large space uptake, new to this site, please let me know if there is a way to make smaller>

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 12/6/14 8:56 PM
Description: Exception in server tick loop

net.shadowmage.ancientwarfare.core.util.Json$JsonParser$JsonParsingException: Did not find name separator : while parsing object
At char index: 87 char: ,
at net.shadowmage.ancientwarfare.core.util.Json$JsonParser.throwUnexpectedException(Json.java:294)
at net.shadowmage.ancientwarfare.core.util.Json$JsonParser.readObject(Json.java:208)
at net.shadowmage.ancientwarfare.core.util.Json$JsonParser.readAbstract(Json.java:173)
at net.shadowmage.ancientwarfare.core.util.Json$JsonParser.readObject(Json.java:211)
at net.shadowmage.ancientwarfare.core.util.Json$JsonParser.readAbstract(Json.java:173)
at net.shadowmage.ancientwarfare.core.util.Json$JsonParser.readObject(Json.java:211)
at net.shadowmage.ancientwarfare.core.util.Json$JsonParser.process(Json.java:126)
at net.shadowmage.ancientwarfare.core.util.Json.parseJson(Json.java:73)
at net.shadowmage.ancientwarfare.core.util.JsonTagReader.parseTagCompound(JsonTagReader.java:44)
at net.shadowmage.ancientwarfare.structure.api.TemplateRule.readTag(TemplateRule.java:105)
at net.shadowmage.ancientwarfare.structure.api.TemplateRule.parseRule(TemplateRule.java:88)
at net.shadowmage.ancientwarfare.structure.api.TemplateRuleBlock.parseRule(TemplateRuleBlock.java:63)
at net.shadowmage.ancientwarfare.structure.template.StructurePluginManager.getRule(StructurePluginManager.java:369)
at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseRule(TemplateParser.java:285)
at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseTemplateLines(TemplateParser.java:184)
at net.shadowmage.ancientwarfare.structure.template.load.TemplateParser.parseTemplate(TemplateParser.java:50)
at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.loadTemplateFromFile(TemplateLoader.java:148)
at net.shadowmage.ancientwarfare.structure.template.load.TemplateLoader.loadTemplates(TemplateLoader.java:101)
at net.shadowmage.ancientwarfare.structure.AncientWarfareStructures.postInit(AncientWarfareStructures.java:139)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:322)
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:279)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 8.1 (amd64) version 6.3
Java Version: 1.7.0_60, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1822026632 bytes (1737 MB) / 1998061568 bytes (1905 MB) up to 1998061568 bytes (1905 MB)
JVM Flags: 2 total; -Xmx2048M -Xms2048M
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v9.05 FML v7.10.25.1206 Minecraft Forge 10.13.0.1206 55 mods loaded, 55 mods active
mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
FML{7.10.25.1206} [Forge Mod Loader](cauldron-1.7.10-1.1206.01.169-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Forge{10.13.0.1206} [Minecraft Forge](cauldron-1.7.10-1.1206.01.169-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ivtoolkit{1.0} [IvToolkit](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
battlegear2{1.0.6.2} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
simpleores{1.4.3} [SimpleOres 2]([1.7.10] SimpleOres 2 Core v1.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
fusionplugin{1.4.3} [SimpleOres 2 Fusion Plugin]([1.7.10] Fusion Plugin v1.4.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
advanceddispensers{1.2.0-b8 for 1.7.10} [Advanced Dispensers Mod](advanceddispensers-1.2.0-b8.for.1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
AncientWarfare{2.3.77-beta-MC1.7.10} [Ancient Warfare Core](ancientwarfare-2.3.77-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
AncientWarfareAutomation{2.3.77-beta-MC1.7.10} [Ancient Warfare Automation](ancientwarfare-2.3.77-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
AncientWarfareNEIPlugin{2.3.77-beta-MC1.7.10} [Ancient Warfare NEI Plugin](ancientwarfare-2.3.77-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
AncientWarfareNpc{2.3.77-beta-MC1.7.10} [Ancient Warfare NPCs](ancientwarfare-2.3.77-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
AncientWarfareStructure{2.3.77-beta-MC1.7.10} [Ancient Warfare Structures](ancientwarfare-2.3.77-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
AncientWarfareVehicle{2.3.77-beta-MC1.7.10} [Ancient Warfare Vehicles](ancientwarfare-2.3.77-beta-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
BaMsGRAVE{1.4.2_01} [BaM's Grave](bamsgrave-1.7.2-1.4.2_01.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
bettervanilla{1.1.1} [BetterVanilla](BetterVanilla-1.7.10-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
CarpentersBlocks{3.3.0} [Carpenter's Blocks](Carpenter's Blocks v3.3.0 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
climatecontrol{0.2} [Climate Control](ClimateControl-0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
BuildMod{v1.0} [Build Mod](CoroUtil-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
CoroAI{v1.0} [CoroAI](CoroUtil-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ExtendedRenderer{v1.0} [Extended Renderer](CoroUtil-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
ConfigMod{v1.0} [Extended Mod Config](CoroUtil-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Crowns{1.2} [Crowns](crowns-1.7.10-1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
CustomSpawner{3.3.0} [DrZhark's CustomSpawner](CustomMobSpawner 3.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
source_code293.digitalxp{0.1.5} [DigitalXP](DigitalXP-1.7.10-0.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
MoCreatures{6.3.0} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v6.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
GregsLighting{1.11.1} [Greg's Lighting](GregsLighting-1.11.1-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Growthcraft{2.1.0a} [Growthcraft](growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar](growthcraft-cellar-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Growthcraft|Apples{2.1.0} [Growthcraft Apples](growthcraft-apples-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo](growthcraft-bamboo-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Growthcraft|Bees{2.1.0} [Growthcraft Bees](growthcraft-bees-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap](growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Growthcraft|Grapes{2.1.0} [Growthcraft Grapes](growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Growthcraft|Hops{2.1.0} [Growthcraft Hops](growthcraft-hops-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Growthcraft|Rice{2.1.0a} [Growthcraft Rice](growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
hidenames{1.1.7} [Hide Names](Hide Names-1.7.10-1.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
HoloInventory{1.8.3.86} [HoloInventory](HoloInventory-1.7.10-1.8.3.86.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
LLadders{0.4.0} [Luppii's Ladders](Ladders-0.4.0-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
MagicWands{1.1.0} [MagicWands](Magic-Wands-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
AS_MultiMine{1.4.2} [Multi Mine](MultiMine-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
natureoverhaul{0.9} [Nature Overhaul](NatureOverhaul-0.9%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
RedstonePasteMod{1.6.2} [Redstone Paste](RedstonePasteMod-1.7.10-1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
shipwrecks_winslow{1.6.2} [Shipwrecks!](shipwrecks_winslow-1.7.2-1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
SlimevoidLib{2.0.4.6} [Slimevoid Library](SlimevoidLibrary-2.0.4.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
SteelIndustries{1.7.10-0.5c} [Steel Industries](SteelIndustries-1.7.10-0.5c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
StevesCarts{2.0.0.b16} [Steve's Carts 2](StevesCarts2.0.0.b16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
TF2Teleporter{1.7.10} [TF2 Teleporter](TF2Teleporter-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
TwilightForest{2.3.2} [The Twilight Forest](twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
weather2{v2.3.6} [weather2](Weather-2.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
YAFM{1.0.3} [Yet Another Food Mod](yafm-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
yegamolchattels{1.1} [Ye Gamol Chattels](YeGamolChattels-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
Profiler Position: N/A (disabled)
Player Count: 0 / 20; []
Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
Type: Dedicated Server (map_server.txt)

**Comment by shadowmage45** [comment] 2014-12-07 17:24
Can you post the template that is causing the crash?  (Cannot locate/fix the problem without that information)

**Comment by ThatPolishKid99** [comment] 2014-12-07 18:21
https://drive.google.com/file/d/0Bxh2Ps65vCsLX0UwOXRQWWowMkE/view?usp=sharing
it is a very large file... but its there!

**Comment by ThatPolishKid99** [comment] 2014-12-07 18:25
however, i have another template, which works just fine, and is almost an exact copy, except in this one, i removed all Greg's Lighting Floodlights, all Carpenter's Blocks Sloped Blocks, and Vanilla signs (Note: the modded blocks didn't copy anyways)

https://drive.google.com/file/d/0Bxh2Ps65vCsLRUV3MzNmaWdWeDA/view?usp=sharing

**Comment by shadowmage45** [comment] 2014-12-08 17:42
I have narrowed this down to being caused by the vanilla signs with quotation marks within their text.

This basically causes a parsing error, when the JSON parser encounters a ", it thinks it is the end of the data, and begins looking for the next element.  It then encounters the second set of ", and begins opening a new object.  When it looks for the closing quote and separator char for the object, it crashes out because it does not find one.

Couple of solutions that I will look into:
A.) Special case the sign-data rule to store sign text in a different manner, and not parse it through the JSON / nbt conversion process.  Would fix the sign rules (but require any existing templates with signs be rescanned).
B.)  (And what I will be aiming to do).  Fix the actual saving and parsing of quoted data within the JSON format.  Use escape chars to denote quotation marks within text data.  Will require validating input data for quotation marks, as well as restoring said data upon deserialization.

**Closed as completed** 2014-12-08 18:14 UTC
