### ISSUE TITLE
Problem with courier

### ISSUE THREAD

**Issue by Russia2013** [P3pp3rF1y/AncientWarfare2#509] opened 2016-09-19 16:24 UTC
I have two problems with couriers. I had a problem where one simply disappeared on me.  I cannot find the courier and he is not showing up on the death list.  The other problem I am having is that when using couriers they will work with the quarries and warehouse for a while but eventually they will simply run by them and not pick anything up from them. I have it where the first 5 stops are quarries  with the option take non match. Then the final stop is the warehouse interface block with deposit non match. Now the courier will not pick anything up from the quarries and deposit them into the warehouse.

**Comment by Bananasrawesome1251** [comment] 2016-10-15 16:30
I have the same problem, except almost all my npcs went missing. I checked the Nether Portal they like to go through, but they weren't there. I also checked every explored chunk of my world and still no luck. I thought it may be a mod compatibility issue. Maybe it's a forge or aw version problem?

**Comment by cosmicdan** [comment] 2016-11-04 06:36
Regarding the NPC not following orders: Are you sure the backpack isn't full? This kind of order loop sounds like they will slowly fill up their capacity, you'd need another deposit command of some sort to dispose of stuff you don't want.

Regarding disappearing:
Are you using Optifine and is this single player? Optifine apparently has some "optimization" to despawn entities and doesn't re-create them properly, I say apparently because I have not made any serious investigation and don't know if it's true. But at least one other person solved their disappearing NPC problem by removing Optifine. Could have been a red herring, though.

This does not happen on dedicated servers, though, at least in my experience - and Optifine doesnt go on servers.

There is a chance that an NPC could, for some reason, be forced to wander outside a town hall range, or their home-point is outside a town hall range (default is a maximum of 100 blocks), and they were killed. If an NPC is killed outside of town hall range then they won't appear in the list.

We have had these kinds of reports before, but I've never been able to reproduce it. Excuse me while I start bashing my head in wondering how I can debug the problem better.

**Comment by Russia2013** [comment] 2016-11-05 03:18
I ended up finding them. They were on the level below. I am building a city like Minas Tirith in Lord of the Rings but underneath the city there are 40 lvls of wheat farms at maximum lvl. They ended up being in the lvl below where there are no stairs to go up to the next lvl. I thought It would be weird they would simply disappear from inside my city.

**Comment by P3pp3rF1y** [comment] 2018-04-28 11:04
I have changed courier logic quite a bit in 1.12 and after the changes i am not seeing any of these issues. And 1.7 is no longer supported so closing.

**Closed as completed by P3pp3rF1y** 2018-04-28 11:04 UTC
